name: Metrics
on:
  schedule: [{cron: "0 */24 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: he-and-her
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_lines: yes
          plugin_stargazers: yes

